### PR TITLE
fix: properly load index.js ES modules

### PR DESCRIPTION
**Pull request by rpastro**
Properly load index.js as an ES module when project has type "module".  Addresses issue #319

### CODE REVIEW

**Comment by rpastro** [comment]
I signed the CLA.

**Comment by rpastro** [comment]
@typhonrt   If you have a chance to take a look, this is the PR I have submitted to address issue #319.

**Comment by rpastro** [comment]
Can anyone from core team please take a look at this pull request?  This  is meant to address issue #319.

**Comment by peternhale** [comment]
@rpastro Thanks for the contribution. I was wondering if you would mind updating your branch and we can review/test.

**Comment by rpastro** [comment]
@peternhale  Sure. I'll try to do it later today.

**Comment by rpastro** [comment]
@peternhale  I updated the PR, but one of the tests is failing. Can you please confirm whether the failure is related to my change? Thanks.

**Comment by peternhale** [comment]
@rpastro I checked previous build for main and all the tests passed. The node version for that particular test run is using node 17.

**Comment by rpastro** [comment]
@peternhale   All tests are passing now.

**Comment by peternhale** [comment]
Thank you @rpastro

**Comment by rpastro** [comment]
@peternhale  Any idea when someone will be able to look at this PR?  Thanks.

**Review by peternhale — CHANGES_REQUESTED** [review]
@rpastro Please add unit tests to cover these

**Comment by zipzapzanigan** [comment]
I am also hitting this bug, when trying to use ESM modules (https://github.com/sindresorhus/p-queue) and trying to use multiple nested commands in the command folder. Would love to have a fix merged soon!

**Comment by rpastro** [comment]
@peternhale   I apologize but I won't have a chance to look into this for the next couple of weeks. I wish you had told me about the unit tests when I was making the updates.

**Pull request closed without merging**
