### PR TITLE
fix: avoid nonExistentFlag error with strict set to false (#606)

### PR DESCRIPTION
**Pull request by mdonnalley**
Fixes https://github.com/oclif/core/issues/616

### CODE REVIEW

**Comment by mdonnalley** [comment]
@SferaDev I merged your branch into this one so that we can get the GHA to run for it (we don't allows actions to run on forks for security purposes)

However, in testing this locally I'm starting to question whether we should merge this change. For context, the purpose of that `NonExistentFlagsError` is to pick up on any flags that don't have a corresponding definition in the command, specifically when `strict = false`. The best example of this would be a misspelled flag, e.g. `my-command arg1 --hekp` would throw because `--hekp` is not a defined flag. 

This was all done in order to fix the problem of oclif not knowing about invalid flags when `strict = false` (see this [issue](https://github.com/oclif/core/issues/526)). Before in v1, `--hekp` in the example above would have wrongly been parsed as argument

If we move forward with your change, then we'll essentially be undoing that fix

Could you elaborate on what you're trying to accomplish? Perhaps I can help you figure out a way around this without having to undo any of the fixes we made in v2

**Comment by SferaDev** [comment]
Sure, let me explain where we hit this problem in v2 and was working properly in v1.

In a `BaseCommand` class that we inherit in all other commands we have a utility method to load a global flag.

```ts
async getProfile(): Promise<Profile> {
    const { flags } = await this.parse({ strict: false, flags: { ...BaseCommand.profileFlag } }, this.argv);
    ...
}
```

In the `argv` there will more flags than the ones we know for the command, hence passing the `strict` set to false so that it loads the one that we want but ignores extra ones.

**Comment by mdonnalley** [comment]
@SferaDev so you have a flag that you want all children of `BaseCommand` to inherit?

If that's the case, you define `baseFlags` in your `BaseCommand` that will serve that purpose. Here's the doc for that https://oclif.io/docs/global_flags

You can see a more robust example of how this can be used here: https://oclif.io/docs/base_class

**Comment by SferaDev** [comment]
Let me give a try to that, I don't recall that doc when we implemented this flag so it must be something recent. Will let you know if it's working as it did with the other mechanism.

In any case, with this change you wouldn't be reverting the fix for https://github.com/oclif/core/issues/526, as the problem was that it parsed the incorrect flag as an argument. To me `strict` in parse shouldn't throw, WDYT?

**Comment by mdonnalley** [comment]
@SferaDev `strict = false` is intended to enable an unknown number of arguments to be passed to a command. It's not intended to be a "don't throw any errors" switch.

But, yes, it would revert the fix for #526 since the fix was done specifically for when `strict = false`. oclif has always known how to handle non-existent flags when `strict = true` (or undefined). The problem was that `strict = false` was allowing non-existent flags to be provided, instead of just allowing an unknown number of arguments.

If we merge your fix as it is, `strict = false` would again allow non-existent to be provided (which we don't want to allow)

Let me know if you need any help with implementing `baseFlags` - I'm happy to help

**Comment by SferaDev** [comment]
Base flags worked fine based on the complex example you showed, fine by me closing this as-is

**Pull request closed without merging**
